# -*- coding: utf-8 -*-
"""Clase_8septiembre2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u90tSb4Li8sJp1T30W2IRcG36Z-CMEw7

<center>

#**COLEGIO SIGLO XXI**
#**PRESENTADO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR: ANA SOFÍA BARAJAS JIMÉNEZ**
#**GRADO DÉCIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?**
# Python es un lenguaje de scripting independiente de plataforma y orientado a objetos, preparado para realizar cualquier tipo de programa, desde aplicaciones Windows a servidores de red o incluso, páginas web. Es un lenguaje interpretado, lo que significa que no se necesita compilar el código fuente para poder ejecutarlo, lo que ofrece ventajas como la rapidez de desarrollo e inconvenientes como una menor velocidad.
#**Fecha de lanzamiento:** Diciembre de 1991
#**Creador:** Guido Van Rossum

#**Recuperado de:**https://desarrolloweb.com/articulos/1325.php
"""

print ("Esto es una suma")
numero_uno = 10
numero_dos = 5
resultado = numero_uno + numero_dos
print (resultado)

print ("Esto es una resta")
numero_uno = 6
numero_dos = 2
resultado = numero_uno - numero_dos
print (resultado)

print ("Esto es una multiplicación")
numero_uno = 4
numero_dos = 4
resultado = numero_uno * numero_dos
print (resultado)

print ("Esto es una división")
numero_uno = 9
numero_dos = 3
resultado = numero_uno / numero_dos
print (resultado)

"""#**Ejercicios de Tipos de Datos Simples**

## Ejercicio 1

Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla en líneas distintas el nombre del usuario tantas veces como el número introducido.
"""

nombre = input("¿Cómo te llamas? ")
n = input("Introduce un número entero: ")
print((nombre + "\n") * int(n))

"""##Ejercicio 2
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tu índice de masa corporal es <imc>' donde 'imc' es el índice de masa corporal calculado redondeado con dos decimales.
"""

peso = input ("¿Cuál es tu peso en kg?")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round (float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es "+str(imc))

"""# **LIBRERÍAS EN PYTHON**

#**LIBRERÍA PANDA**
"""